# Generated by Django 4.2.1 on 2023-05-29 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_daymodel_hourmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DayModel',
        ),
        migrations.DeleteModel(
            name='HourModel',
        ),
    ]
