# Generated by Django 4.2.1 on 2023-05-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0005_alter_hourmodel_all'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all', models.CharField(blank=True, max_length=10000000000, null=True)),
            ],
        ),
    ]
