# Generated by Django 4.2.1 on 2023-05-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0006_daymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daymodel',
            name='all',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hourmodel',
            name='all',
            field=models.TextField(blank=True, null=True),
        ),
    ]
